{
 "title": "NGINX Plus Ingress Controller",
 "description": "A rich collection of Prometheus metrics from NGINX Plus Kubernetes Ingress Controller",
 "tags": [
  "nginx",
  "plus",
  "ingress"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container_name!=\"POD\"},namespace)"
    }
   },
   {
    "name": "controller",
    "label": "NGINX Plus Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_ingress_resources_total, kubernetes_pod_name) "
    }
   },
   {
    "name": "server_zone",
    "label": "Server Zone",
    "query": {
     "query": "label_values(nginx_ingress_nginxplus_server_zone_processing,server_zone)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(nginx_ingress_nginxplus_upstream_server_state,server)"
    }
   },
   {
    "name": "upstream",
    "label": "Upstream Server",
    "query": {
     "query": "label_values(nginx_ingress_nginxplus_upstream_server_state,upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Environment Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Plus Reload",
   "type": "stat",
   "description": "Status of the last NGINX Plus reload.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_last_reload_status{kubernetes_pod_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Reloads",
   "type": "stat",
   "description": "Number of successful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reloads_total{kubernetes_pod_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Reload Errors",
   "type": "stat",
   "description": "Number of unsuccessful NGINX Plus reloads.",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_reload_errors_total{kubernetes_pod_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Bytes received from clients and sent to clients.",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( rate(nginx_ingress_nginxplus_server_zone_received[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum( rate(nginx_ingress_nginxplus_server_zone_sent[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Last Reload Time",
   "type": "stat",
   "description": "Last controller reload milliseconds.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_last_reload_milliseconds{kubernetes_pod_name=\"$controller\"})"
    }
   ]
  },
  { "title": "Ingress Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "HTTP Request Volume",
   "type": "stat",
   "description": "Total http requests per second looking back over the last 5 minutes.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( irate(nginx_ingress_nginxplus_http_requests_total{kubernetes_pod_name=\"$controller\"}[5m]))"
    }
   ]
  },
  {
   "title": "Ingress Count",
   "type": "stat",
   "description": "Total number of deployed Ingress .",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_ingress_resources_total)"
    }
   ]
  },
  {
   "title": "Zone Request Volume",
   "type": "stat",
   "description": "Total http requests per second looking back over the last 5 minutes across all server zones.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( irate(nginx_ingress_nginxplus_server_zone_requests{kubernetes_pod_name=\"$controller\"}[5m]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Handled Ingress Resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_ingress_resources_total{type=\"master\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum(nginx_ingress_controller_ingress_resources_total{type=\"minion\"})",
     "legendFormat": "minion"
    },
    {
     "expr": "sum(nginx_ingress_controller_ingress_resources_total{type=\"regular\"})",
     "legendFormat": "regular"
    }
   ]
  },
  {
   "title": "Success Rates Over Time",
   "type": "graph",
   "description": " 1|2|3xx response status codes.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=\"1xx\"}[5m])) by (ingress)",
     "legendFormat": "Informational"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=\"3xx\"}[5m]))",
     "legendFormat": "Redirection"
    }
   ]
  },
  {
   "title": "Error Rates Over Time",
   "type": "graph",
   "description": " 4|5xx response status codes.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=~\"[4].*\"}[2m]))",
     "legendFormat": "Client Errors"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code=~\"[5].*\"}[2m]))",
     "legendFormat": "Server Errors"
    }
   ]
  },
  {
   "title": "Ingress State",
   "type": "stat",
   "description": "Current State of the NGINX Ingress Controller.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_nginxplus_up{kubernetes_pod_name=\"$controller\"})"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "stat",
   "description": "Non-4|5xx response status codes divided by total number of response status codes.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_server_zone_responses{code!~\"[4-5].*\"}[5m])) / sum(rate(nginx_ingress_nginxplus_server_zone_responses[5m]))"
    }
   ]
  },
  { "title": "Upstream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Upstream Success Rate",
   "type": "graph",
   "description": "Upstream success rate Over Time.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{code=\"1xx\"}[5m]))",
     "legendFormat": "Informational"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{code=\"3xx\"}[5m]))",
     "legendFormat": "Redirection"
    }
   ]
  },
  {
   "title": "Upstream Server Count",
   "type": "stat",
   "description": "Total number of upstream servers.",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (nginx_ingress_nginxplus_upstream_server_active)"
    }
   ]
  },
  {
   "title": "Upstream Error Rate",
   "type": "graph",
   "description": " 4|5xx Status Codes",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{code=~\"[4].*\"}[2m]))",
     "legendFormat": "Client Errors"
    },
    {
     "expr": "sum(rate(nginx_ingress_nginxplus_upstream_server_responses{code=~\"[5].*\"}[2m]))",
     "legendFormat": "Server Errors"
    }
   ]
  },
  {
   "title": "Upstream Server State",
   "type": "stat",
   "description": "Current State of the upstream servers.",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_nginxplus_upstream_server_state)"
    }
   ]
  },
  { "title": "SSL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "SSL Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Handshakes"
    },
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_handshakes_failed{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Failed"
    },
    {
     "expr": "irate(nginx_ingress_nginxplus_ssl_sessions_reuses{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} Reuses"
    }
   ]
  }
 ]
}