apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-bg
spec:
  rules:
  - host: blue.bddemo.udf
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-blue
          servicePort: 80
  - host: green.bddemo.udf
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-green
          servicePort: 80
